# Generated by Django 6.0.4 on 2026-04-20 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_lesson_video_url_guild_guildmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='guildmessage',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
    ]
