# Generated by Django 6.0.4 on 2026-04-20 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_guildmessage_is_urgent'),
    ]

    operations = [
        migrations.AddField(
            model_name='guildmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='guild_files/'),
        ),
    ]
